### ISSUE TITLE
What's your favorite fictional character? 

### ISSUE THREAD

**Issue by arthurvr** [incanus/ama#1]

**Comment by incanus** [comment]
This will sound a little clichéd, especially in light of the more recent movies, but I've always been inspired by Gandalf since reading the Lord of the Rings nearly twenty-five years ago. In fact, my username [comes from it](http://tolkiengateway.net/wiki/Gandalf/Names#Inc.C3.A1nus). 

## 

> _“He that breaks a thing to find out what it is has left the path of wisdom.”_

Not necessarily applicable to reverse-engineering, however. 

## 

The qualities I could relate to most (and, when younger or even now, aspire to) are patience, wisdom, a bit of urgency, and a tendency towards dark humor while remaining an optimist. I like to inspire, and to connect people, and to enable them to do things, and study lore and history and relationships of people, things, and systems. Mercy, pity, and empathy are important, too. 

> _“Many that live deserve death. And some that die deserve life. Can you give it to them? Then do not be too eager to deal out death in judgement.”_

## 

I like the effect and impression he had on others: 

> Gildor: _"That Gandalf should be late, does not bode well. But it is said: "Do not meddle in the affairs of Wizards, for they are subtle and quick to anger." The choice is yours: to go or wait."_
> 
> Frodo: _"And it is also said, 'Go not to the elves for counsel, for they will say both no and yes.'"_

Though this was said _about_ Gandalf, I've always liked it, as well as the slightly more modernized and wizard-less version: 

> _Do not meddle in the affairs of dragons, for you are crunchy and good with ketchup._

## 

https://web.archive.org/web/20020721080645/http://codesorcery.net/

**Comment by arthurvr** [comment]
Neat answer!
