### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [incanus/ama#4]

**Comment by incanus** [comment]
Thanks for the question @jedireza. No, I don't currently in a formal capacity, but have in the past. These days I spend a good amount of time helping to grow internally at [Mapbox](http://mapbox.com) as the mobile lead and someone who's been on the team since the start. This includes trying to help people grow as leaders but also as programmers, particularly newly getting into mobile development from other areas or even no programming experience.
