### ISSUE TITLE
Switch to xCode 2.0 JSon file unable to load.

### ISSUE THREAD

**Issue by glutonsrn** [incanus/ama#7]
Hi,

recently i saw one of your project about "PointTest" recently i am developing some map with multiple annotation, so i needed JSON for multiple annotation purposes. But when i realise for swift 2.0 they changed some of the code inside for NSJSONSerializatio. Because i am quite new for it, can you please guild me?

Thank so much !

**Comment by incanus** [comment]
Hi @JjLim1224, I'm not sure of the specifics of your issue, but yes, changes in optionals behavior for Swift 2.0 would likely affect JSON parsing with `NSJSONSerialization`. I'd recommend you write with more details to help@mapbox.com if you are using Mapbox for this, otherwise maybe check out how we parse JSON in [`MapboxGeocoder.swift`](https://github.com/mapbox/MapboxGeocoder.swift/blob/master/MBGeocoder/MapboxGeocoder.swift) for Swift 2.0 now.
